[project]
name = "ado-ray-tune"
dependencies = [
  "bayesian-optimization>=1.4.0",
  "nevergrad>=1.0.12",
  "paretoset>=1.2.4",
  "ray[tune]>=2.9",
  "scipy>=1.15.3",
]
dynamic = ["version"]

[project.entry-points."ado.operators"]
ado-ray-tune = "ado_ray_tune.operator"
rifferla = "ado_ray_tune.rifferla"

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "../../../"
local_scheme = "node-and-timestamp"
