ARG PYTHON_VERSION=310
ARG CUDA_VERSION=cu121
ARG BASE_IMAGE=quay.io/ado/ado:latest-py${PYTHON_VERSION}-${CUDA_VERSION}
FROM $BASE_IMAGE

# Pass SOURCE_DATE_EPOCH to guarantee that all the wheels built will use
# the same timestamp.
ARG SOURCE_DATE_EPOCH

## Install ado-vllm-performance
RUN export SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} && \
    cd ado && \
    uv pip install --system \
    'plugins/actuators/vllm_performance'
