[project]
name = "ado-sfttrainer"
description = "An actuator for benchmarking fine-tuning of foundation models"  # Change to describing your actuator
readme = "ado_actuators/sfttrainer/README.md"
requires-python = ">=3.10,<3.13"
dependencies = ["aim>=3.23.0", "jwt", "psutil", "transformers>=4.44.2"]
dynamic = ["version"]

[project.scripts]
sfttrainer_check_metrics_stability = "ado_actuators.sfttrainer.scripts.check_metrics_stability:app"
sfttrainer_download_hf_weights = "ado_actuators.sfttrainer.scripts.download_hf_weights:app"
sfttrainer_generate_dataset_text = "ado_actuators.sfttrainer.scripts.generate_dataset:app"
sfttrainer_generate_dataset_vision = "ado_actuators.sfttrainer.scripts.generate_vision_dataset:app"

[project.entry-points."ado.actuators"]
sfttrainer = "ado_actuators.sfttrainer.actuators:SFTTrainer"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["ado_actuators"]

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
pattern-prefix = "sfttrainer/"
fallback-version = "0.0.0"
format-jinja = """
{%- set metadata = [
    distance != 0 and "g" ~ commit,
    distance != 0 and "d" ~ timestamp,
    dirty and "dirty"
] -%}
{{ serialize_pep440(
    distance == 0 and base or bump_version(base),
    dev=distance or None,
    metadata=metadata | select | list
) }}
"""
