[project]
name = "ado-trim"
description = "TRIM (Transfer Refined Iterative Modeling) builds an accurate predictive model from a small dataset by iteratively sampling a Discovery Space."
readme = "README.md"
# autogluon==1.5 requires pyarrow < 21, which is
# incompatible with Python 3.14
# ref: https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py#L22
requires-python = ">=3.10,<3.14"
dependencies = [
  "ado-core>=2.0.0",
  "autogluon-tabular[catboost,xgboost]==1.6.1; python_full_version < '3.14'",
  "numpy",
  "pandas>=2.2.0",
  "scikit-learn",
]
dynamic = ["version"]

[project.entry-points."ado.operators"]
trim = "trim.operator"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/trim"]

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
pattern-prefix = "trim/"
fallback-version = "0.0.0"
format-jinja = """
{%- set metadata = [
    distance != 0 and "g" ~ commit,
    distance != 0 and "d" ~ timestamp,
    dirty and "dirty"
] -%}
{{ serialize_pep440(
    distance == 0 and base or bump_version(base),
    dev=distance or None,
    metadata=metadata | select | list
) }}
"""
