[project]
name = "trim"
dynamic = ["version"]
description = "TRIM (Transfer Refined Iterative Modeling) efficiently samples a Discovery Space to build accurate predictive models with minimal data."
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "autogluon-tabular[catboost,xgboost]==1.5",
    "numpy",
    "pandas>=2.2.0",
    "scikit-learn",
]

[project.entry-points."ado.operators"]
trim = "trim.operator"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
fallback-version = "0.0.0"
tagged-metadata = true
dirty = true
bump = true