"""
"orchestrator/api/rest.py"

This module defines the FastAPI application and the Ray Serve deployment
for the ADO (Accelerated Discovery Orchestrator) REST API.

The module performs the following tasks:

* Creates a FastAPI instance and includes the API routers for the
latest and v0 endpoints.
* Configures coloured logging via :func:`orchestrator.utilities.logging.configure_logging`.
* Starts an asynchronous background task that watches the shared queue
  for MeasurementRequests generated by the actuators and updates the in-memory request storage.
* Exposes the API as a Ray Serve deployment, so it can be served in a Ray Serve cluster.

The code uses the ``serve`` decorator from Ray Serve to expose the
``FastAPI`` instance to the Ray Serve traffic routing system.
"""

# Copyright (c) IBM Corporation
# SPDX-License-Identifier: MIT
import asyncio

from fastapi import FastAPI
from ray import serve

from orchestrator.api.routers.latest import latest
from orchestrator.api.routers.v0 import v0
from orchestrator.api.state.queue import watch_queue
from orchestrator.utilities.logging import configure_logging

app = FastAPI()

# Add routers for API endpoints.
app.include_router(latest.router, prefix="/api")
app.include_router(v0.router, prefix="/api")


@serve.deployment
@serve.ingress(app)
class AdoRESTApi:
    """Ray Serve deployment that hosts the FastAPI application.

    The deployment creates a background coroutine that watches the
    orchestration queue. It keeps a reference to the task to avoid
    the CPython issue <https://github.com/python/cpython/issues/88831>,
    where a task created with :func:`asyncio.create_task` may be
    garbage-collected prematurely.
    """

    def __init__(self):
        """Initialise logging and start the background queue watcher.

        The constructor performs two main actions:

        1. Calls :func:`orchestrator.utilities.logging.configure_logging`
           to set up coloured logging configuration.
        2. Creates an asyncio task that runs :func:`watch_queue`
           which continuously polls the shared queue for
           incoming MeasurementRequests.
        """
        configure_logging()

        # Keep reference to the task to avoid CPython garbage-collection
        # bug <https://github.com/python/cpython/issues/88831>.
        self.task_reference = asyncio.get_event_loop().create_task(watch_queue())


# Bind the deployment for use by Ray Serve.
ado_rest_api = AdoRESTApi.bind()
