# Copyright (c) IBM Corporation
# SPDX-License-Identifier: MIT

import uuid
from typing import Annotated, Any

import pydantic
from pydantic import BeforeValidator

from orchestrator.core.actuatorconfiguration.config import ActuatorConfiguration
from orchestrator.core.resources import ADOResource, CoreResourceKinds
from orchestrator.utilities.pydantic import default_if_none


class ActuatorConfigurationResource(ADOResource):

    @staticmethod
    def _identifier_from_data(data: dict[str, Any]) -> str:
        return f"{data['kind'].value}-{data['config'].actuatorIdentifier}-{str(uuid.uuid4())[:8]}"

    version: str = "v1"
    kind: CoreResourceKinds = CoreResourceKinds.ACTUATORCONFIGURATION
    config: ActuatorConfiguration
    identifier: Annotated[
        str,
        pydantic.Field(
            default_factory=_identifier_from_data,
            description="Unique identifier of the resource. "
            "Autogenerated based on kind if not provided",
        ),
        BeforeValidator(default_if_none),
    ]
