[project]
name = "ado-cplex-mip"
description = "ado custom experiment for benchmarking CPLEX MIP solver performance across parameter configurations"
dependencies = [
  "ado-core>=2.0.0",
  "cplex",
]
dynamic = ["version"]

[project.entry-points."ado.custom_experiments"]
cplex_mip = "cplex_mip_experiments.solve_mip"

[dependency-groups]
dev = [
  "pytest>=9.0.1",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["cplex_mip_experiments"]

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
pattern-prefix = "cplex-mip/"
fallback-version = "0.0.0"
format-jinja = """
{%- set metadata = [
    distance != 0 and "g" ~ commit,
    distance != 0 and "d" ~ timestamp,
    dirty and "dirty"
] -%}
{{ serialize_pep440(
    distance == 0 and base or bump_version(base),
    dev=distance or None,
    metadata=metadata | select | list
) }}
"""
