[project]
name = "robotic_lab"  # Change to your preferred name, along with the actual package
description = "A template for creating an actuator"  # Change to describing your actuator
dependencies = [
  "ado-core",
]
dynamic = ["version"]

[project.entry-points."ado.actuators"]
robotic_lab = "robotic_lab_actuator.actuator:RoboticLab"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/robotic_lab_actuator"]

# Required when added as a workspace package.
# Do not include it if you're developing an actuator outside of the ado repo
[tool.uv.sources]
ado-core = { workspace = true }

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
pattern-prefix = "example-actuator/"
fallback-version = "0.0.0"
format-jinja = """
{%- set metadata = [
    distance != 0 and "g" ~ commit,
    distance != 0 and "d" ~ timestamp,
    dirty and "dirty"
] -%}
{{ serialize_pep440(
    distance == 0 and base or bump_version(base),
    dev=distance or None,
    metadata=metadata | select | list
) }}
"""
