# Copyright IBM Corporation 2025, 2026
# SPDX-License-Identifier: MIT


import os
import pathlib
from collections.abc import Callable, Generator

import pytest
import sqlalchemy
import testcontainers.mysql
import yaml
from sqlalchemy.pool import NullPool
from typer.testing import CliRunner

import ado.core
import ado.metastore
import ado.metastore.project
import ado.metastore.sqlstore
from ado.cli.core.cli import app as ado_app
from ado.core import DiscoverySpaceResource
from ado.core.resources import CoreResourceKinds
from ado.metastore.project import ProjectContext
from ado.metastore.sqlstore import SQLStore
from ado.modules.module import ModuleConf, ModuleTypeEnum
from ado.utilities.output import pydantic_model_as_yaml


@pytest.fixture
def orchestrator_project_name() -> str:
    return "spark-opt"


@pytest.fixture(
    params=[
        ModuleTypeEnum.ACTUATOR,
        ModuleTypeEnum.SAMPLE_STORE,
        ModuleTypeEnum.OPERATION,
    ]
)
def module_config(request: pytest.FixtureRequest) -> ModuleConf:
    return ModuleConf(moduleType=request.param)


@pytest.fixture(scope="session")
def mysql_test_password() -> str:
    return "a-possible-password-for-mysql"


@pytest.fixture(scope="session")
def mysql_test_port() -> int:
    return 3306


@pytest.fixture(scope="session")
def mysql_test_instance(
    mysql_test_password: str,
    mysql_test_port: int,
) -> testcontainers.mysql.MySqlContainer:

    # AP 20/03/2024: Ryuk is not connecting locally and we
    # don't really need it since we're using the context manager
    # ref: https://github.com/testcontainers/testcontainers-python/pull/314
    os.environ["TESTCONTAINERS_RYUK_DISABLED"] = "true"

    # We need to use root as we need to create databases on-the-fly
    with testcontainers.mysql.MySqlContainer(
        image="mirror.gcr.io/mysql:8",
        username="root",
        root_password=mysql_test_password,
        password=mysql_test_password,
        port=mysql_test_port,
        dialect="pymysql",
    ) as mysql_instance:
        yield mysql_instance


@pytest.fixture
def valid_ado_mysql_context_yaml(
    random_identifier: Callable[[], str],
    mysql_test_password: str,
    mysql_test_port: int,
    mysql_test_instance: testcontainers.mysql.MySqlContainer,
) -> str:
    random_id = random_identifier()
    db_name = f"pytest_{random_id}"

    # NullPool disables connection pooling for this one-shot DDL engine.
    # Without it, sqlalchemy.create_engine() opens a pooled connection that is
    # never returned to any cache and never explicitly disposed — it leaks for
    # the lifetime of the OS TCP state (~4 min TIME_WAIT).
    with sqlalchemy.create_engine(
        mysql_test_instance.get_connection_url(), poolclass=NullPool
    ).begin() as connection:
        connection.execute(sqlalchemy.text(f"CREATE DATABASE IF NOT EXISTS {db_name}"))

    return f"""
    project: "{db_name}"
    metadataStore:
        scheme: "mysql+pymysql"
        host: {mysql_test_instance.get_container_host_ip()}
        port: {mysql_test_instance.get_exposed_port(mysql_test_port)}
        password: {mysql_test_password}
        user: root
        database: "{db_name}"
        sslVerify: false
    """


@pytest.fixture
def valid_ado_sqlite_context_yaml(random_identifier: Callable[[], str]) -> str:
    # AP: adding a string before random_identifier as it would
    # otherwise fail validation if it's only numbers
    project_id = f"sqlite-{random_identifier()}"
    yield f"""
        metadataStore:
          database: {project_id}
          path: {project_id}.db
          scheme: sqlite
          sslVerify: false
        project: {project_id}
    """
    pathlib.Path(f"{project_id}.db").unlink(missing_ok=True)


@pytest.fixture
def valid_ado_mysql_project_context(
    valid_ado_mysql_context_yaml: str,
) -> Generator[ado.metastore.project.ProjectContext, None, None]:
    """Provide a MySQL ProjectContext for one test, then release its engine.

    Each test that uses MySQL gets a unique database name (generated by
    random_identifier()), which means a unique connection URL, which means
    engine_for_sql_store creates a brand-new SQLAlchemy Engine — and its
    connection pool — for every test.  Without explicit teardown those pools
    accumulate across the session: with pytest-xdist running N workers each
    holding M per-test engines, the simultaneous open connections easily
    exceed MySQL's default max_connections (151).

    The teardown here looks up the engine for this test's URL in the shared
    _engine_cache, removes it so the cache stays consistent, and calls
    engine.dispose() to close all pooled connections immediately rather than
    waiting for OS TCP TIME_WAIT to expire.
    """
    from ado.metastore.sql.utils import _engine_cache

    context = ado.metastore.project.ProjectContext.model_validate(
        yaml.safe_load(valid_ado_mysql_context_yaml)
    )
    yield context

    # context.metadataStore.url().unicode_string() is the exact key used by
    # engine_for_sql_store to populate _engine_cache, so the pop is precise:
    # it only disposes the engine for this test's unique database.
    db_url = context.metadataStore.url().unicode_string()
    engine = _engine_cache.pop(db_url, None)
    if engine is not None:
        engine.dispose()


@pytest.fixture
def valid_ado_sqlite_project_context(
    valid_ado_sqlite_context_yaml: str,
) -> ado.metastore.project.ProjectContext:
    """Fixture that provides SQLite project context"""
    return ado.metastore.project.ProjectContext.model_validate(
        yaml.safe_load(valid_ado_sqlite_context_yaml)
    )


@pytest.fixture(params=["mysql", "sqlite"])
def valid_ado_project_context(
    valid_ado_mysql_project_context: ado.metastore.project.ProjectContext,
    valid_ado_sqlite_project_context: ado.metastore.project.ProjectContext,
    request: pytest.FixtureRequest,
) -> ado.metastore.project.ProjectContext:
    """Fixture that provides both MySQL and SQLite project contexts via parametrization"""
    return (
        valid_ado_sqlite_project_context
        if request.param == "sqlite"
        else valid_ado_mysql_project_context
    )


@pytest.fixture
def create_active_ado_context() -> Callable[
    [CliRunner, pathlib.Path, ProjectContext], None
]:

    def _create_active_ado_context(
        runner: CliRunner,
        path: pathlib.Path,
        project_context: ProjectContext,
    ) -> None:
        context_file = path / "test_context.yaml"
        context_file.write_text(pydantic_model_as_yaml(project_context))

        creation_result = runner.invoke(
            ado_app,
            [
                "--override-ado-app-dir",
                str(path),
                "create",
                "context",
                "-f",
                context_file,
            ],
        )
        assert creation_result.exit_code == 0

        activation_result = runner.invoke(
            ado_app,
            [
                "--override-ado-app-dir",
                str(path),
                "context",
                project_context.project,
            ],
        )
        assert activation_result.exit_code == 0

        return

    return _create_active_ado_context


@pytest.fixture(scope="module", params=["mysql", "sqlite"])
def ado_test_file_project_context(request: pytest.FixtureRequest) -> ProjectContext:

    import yaml

    if request.param == "sqlite":
        path = "tests/sqlite_test_context.yaml"
    else:
        path = "tests/mysql_test_context.yaml"

    with open(path) as f:
        return ProjectContext.model_validate(yaml.safe_load(f))


@pytest.fixture
def resource_store(
    valid_ado_project_context: ProjectContext,
) -> ado.metastore.sqlstore.SQLStore:

    return ado.metastore.sqlstore.SQLStore(project_context=valid_ado_project_context)


@pytest.fixture(params=list(CoreResourceKinds))
def resource_type(request: pytest.FixtureRequest) -> CoreResourceKinds:
    return request.param


@pytest.fixture
def discovery_space_resource_and_store(
    resource_store: SQLStore,
) -> (DiscoverySpaceResource, SQLStore):
    """Returns a DiscoverySpace resource that can be used to test additions"""

    # Return an existing discovery space conf
    identifiers = resource_store.getResourceIdentifiersOfKind(
        kind=CoreResourceKinds.DISCOVERYSPACE.value
    )
    return (
        resource_store.getResource(
            identifier=identifiers["IDENTIFIER"][0],
            kind=CoreResourceKinds.DISCOVERYSPACE,
        ),
        resource_store,
    )


@pytest.fixture
def active_contest_test_sample_store_resource(
    ado_test_file_project_context: ProjectContext,
) -> ado.core.samplestore.resource.SampleStoreResource:

    return ado.core.samplestore.resource.SampleStoreResource(
        config=ado.core.samplestore.config.SampleStoreConfiguration(
            specification=ado.core.samplestore.config.SampleStoreSpecification(
                module=ado.core.samplestore.config.SampleStoreModuleConf(
                    moduleClass="SQLSampleStore",
                    moduleName="ado.core.samplestore.sql",
                ),
                storageLocation=ado_test_file_project_context.metadataStore,
            )
        ),
    )
