[project]
name = "ado-vllm-performance"
description = "VLLM performance testing actuator for ado"
readme = "README.md"
requires-python = ">=3.10,<3.15"
keywords = ["ado", "benchmarking", "llm", "performance", "testing", "vllm"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Testing",
]
dependencies = [
  "ado-core>=2.0.0",
  "datasets>=2.20.0",  # Required to avoid uv/pip to resolve to a version of datasets that is not compatible with vllm
  "kubernetes>=31.0.0,!=36.0.0",
]
dynamic = ["version"]

[project.urls]
Changelog = "https://github.com/IBM/ado/blob/main/CHANGELOG.md"
Homepage = "https://ibm.github.io/ado/"
Issues = "https://github.com/IBM/ado/issues"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/IBM/ado"

[project.entry-points."ado.actuators"]
vllm_performance = "ado_actuators.vllm_performance.actuator:VLLMPerformanceTest"

[project.optional-dependencies]
guidellm = [
  "guidellm>=0.5.3",
]

vllm = [
  # AP 02/07/2026
  # Scanners are flagging opencv-python-headless==5.0.0.93 as
  # potentially malicious. While we think it's a false positive,
  # we use the <5 qualifier to prevent the major OpenCV bump.
  "opencv-python-headless<5",
  "vllm>=0.12.0,!=0.15.*;sys_platform!='darwin'",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["ado_actuators"]

# Required when added as a workspace package
[tool.uv.sources]
ado-core = { workspace = true }

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
pattern = "default-unprefixed"
pattern-prefix = "vllm-performance/"
fallback-version = "0.0.0"
format-jinja = """
{%- set metadata = [
    distance != 0 and "g" ~ commit,
    distance != 0 and "d" ~ timestamp,
    dirty and "dirty"
] -%}
{{ serialize_pep440(
    distance == 0 and base or bump_version(base),
    dev=distance or None,
    metadata=metadata | select | list
) }}
"""
