[project]
name = "profile_space"
requires-python = ">=3.10,<3.14"
# fg-data-profiling's latest release (4.19.1)
# requires numba<0.63 which is incompatible with
# Python 3.14
dependencies = ["fg-data-profiling"]
dynamic = ["version"]

[project.entry-points."ado.operators"]
profile_space = "profile_space.operator"

[tool.setuptools_scm]
root = "../../../"
local_scheme = "node-and-timestamp"
