[project]
name = "anomalous_series"
dependencies = []
dynamic = ["version"]

[project.entry-points."ado.operators"]
anomalous_series = "anomalous_series.operator"

[tool.setuptools_scm]
root = "../../../"
local_scheme = "node-and-timestamp"

[tool.setuptools_scm.tag]
regex = "^(?:[^/]+/)?(?P<version>[vV]?\\d+(?:\\.\\d+)*)$"
